### ISSUE TITLE
The well positions are not accurate after system reboot

### ISSUE THREAD

**Issue by legendPerceptor** [legendPerceptor/BatteryLab#4]
Our assembly robot consists of a Meca500 robotic arm and a Zaber linear rail. The Meca500 is on the top of the linear rail. We logged the manually aligned positions of each component tray in [well_positions.yaml](https://github.com/legendPerceptor/BatteryLab/blob/main/ros2_ws/src/assembly_robot/yaml/well_positions.yaml). It takes a significant amount of time to obtain the constants because it requires 16 manual positions for each tray and we have 8 trays in total.

Now the big problem is that sometimes the positions are not precise after a system reboot. Every position is off for a few millimeters. It feels like an error combined by the imprecise movement of the linear rail and the Meca500. I don't know what the cause is. Both robot should be quite precise according to their description: Meca500 is of 0.005 mm position repeatability, and the specific Zaber rail we have (X-LRT1500BL-E08C) has an accuracy of 375 µm. The error should be way below 1mm. But this problem happened over and over and is a nightmare to deal with.

![assembly robot](https://github.com/legendPerceptor/BatteryLab/raw/main/figures/assembly_robot.png)

What could be the potential cause? What solutions do we have to deal with this problem?

**Comment by legendPerceptor** [comment]
I wonder if the back-and-forth movement of the linear rail will lead to a higher error. I sometimes used the button on the rail to control the slider's movement. I wonder if the hardware control of the linear rail changes the software-level behavior.

Another Meca500 is fixed on the table and it seems to be pretty precise for the battery crimping movement. I suspect the imprecision comes from the linear rail more than the Meca500.

**Comment by LuckierDodge** [comment]
Does the linear rail have a built-in homing functionality or zero point? We have a linear rail in one of our autonomous labs that we have to make sure we home it before we capture any positions or after any system reboot in order to have reliable localization. We quickly got into the habit of homing it at the start of workflows.

**Comment by legendPerceptor** [comment]
I'll double-check the homing situation. In [ZaberRail.py](https://github.com/legendPerceptor/BatteryLab/blob/6c7a2130fcd4e77fbec106fa7c248bbf343c8774/BatteryLab/robots/ZaberRail.py#L50), there is such logic to ensure the linear rail is homed when it is initially connected.

**Comment by legendPerceptor** [comment]
It looks like an installation error. I reinstalled everything and the problem did not reappear when rebooting different parts of the system. It was because 2 screws in the adapter plate were not tight enough.
